# -*- coding: utf-8 -*-
"""Mask_Detection(CNN)_3_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ea3aC5bHIImO_U6V6I27hRjksulc_pjD
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d 'vijaykumar1799/face-mask-detection'

import zipfile
with zipfile.ZipFile('/content/face-mask-detection.zip','r') as zip_ref:
  zip_ref.extractall("/content/dataset_org")

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img,img_to_array
from tensorflow.keras.applications.efficientnet_v2 import EfficientNetV2B3,preprocess_input
import os

DIRECTORY= '/content/dataset_org/Dataset'

df_list = []

for lable in os.listdir(DIRECTORY):
  path = os.path.join(DIRECTORY,lable)
  for img in os.listdir(path):
    filepath = os.path.join(path,img)
    lable = lable

    df_list.append([filepath,lable])

df = pd.DataFrame(df_list,columns=['filepath','lable'])



from sklearn.model_selection import train_test_split
train_df,test_df = train_test_split(df,stratify=df['lable'],random_state=42)

train_data_gen = ImageDataGenerator(
    preprocessing_function = preprocess_input,
    rotation_range = 20,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    horizontal_flip = True,
    zoom_range = 0.15
    )

test_data_gen = ImageDataGenerator(
    preprocessing_function = preprocess_input
)

train_generator = train_data_gen.flow_from_dataframe(
    train_df,
    x_col = 'filepath',
    y_col = 'lable',
    target_size = (224,224),
    class_mode = 'categorical',
    shuffle = True
)

test_generator = test_data_gen.flow_from_dataframe(
    test_df,
    x_col = 'filepath',
    y_col = 'lable',
    target_size = (224,224),
    class_mode = 'categorical',
    shuffle = False
)

from tensorflow.keras.layers import Dense,Input,Dropout,BatchNormalization,GlobalMaxPooling2D
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model

base_model = EfficientNetV2B3(weights='imagenet', include_top = False, input_shape=(224,224,3))
base_model.trainable = False
inputs = Input(shape = (224,224,3))

x = base_model(inputs,training = False)
x = GlobalMaxPooling2D()(x)

x = Dense(128,activation = 'relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.2)(x)

outputs = Dense(3,activation = 'softmax')(x)

model = Model(inputs,outputs)

model.summary()

plot_model(model,show_shapes=True)

model.compile(optimizer='adam',loss = 'categorical_crossentropy', metrics=['accuracy'])

history = model.fit(train_generator,epochs=3,validation_data=test_generator,verbose=1)

model.save('mask_detection.keras')

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input

# Path to a single test image
img_path = '/content/young-man-wearing-medical-mask-260nw-1770304052.webp'

# Load image, resize to model input
img = image.load_img(img_path, target_size=(224, 224))

# Convert to array and expand dims (batch size = 1)
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# Preprocess for EfficientNetV2
img_array = preprocess_input(img_array)

# Make prediction
pred = model.predict(img_array)  # shape = (1, 3)

# Apply softmax to interpret as probabilities
# (if your model already ends with softmax, this is optional)
probabilities = pred[0]  # shape = (3,)

# Map indices to class names
class_names = ['Mask_Incorrect', 'Mask', 'No_Mask']

# Find predicted class
predicted_index = np.argmax(probabilities)
predicted_class = class_names[predicted_index]

print("Predicted class:", predicted_class)
print("Class probabilities:", probabilities)