# -*- coding: utf-8 -*-
"""car_damage(CNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WbCm-KpU3XRkPvmVR5Ye3mXGV4BXmLu
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d 'anujms/car-damage-detection'

import zipfile
with zipfile.ZipFile('/content/car-damage-detection.zip','r') as zip_ref:
  zip_ref.extractall("/content/dataset_org")

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img,img_to_array
from tensorflow.keras.applications.efficientnet_v2 import EfficientNetV2B3,preprocess_input
import os

DIRECTORY_TRAIN = '/content/dataset_org/data1a/training'
DIRECTORY_TEST = '/content/dataset_org/data1a/training'

train_df = []
test_df = []

for lable in os.listdir(DIRECTORY_TRAIN):
  path = os.path.join(DIRECTORY_TRAIN,lable)
  for img in os.listdir(path):
    filepath = os.path.join(path,img)
    lable = lable

    train_df.append([filepath,lable])


for lable in os.listdir(DIRECTORY_TEST):
  path = os.path.join(DIRECTORY_TEST,lable)
  for img in os.listdir(path):
    filepath = os.path.join(path,img)
    lable = lable

    test_df.append([filepath,lable])

train_df = pd.DataFrame(train_df, columns=['filepath','label'])
test_df = pd.DataFrame(test_df, columns=['filepath','label'])

train_df

train_df['label'] = train_df['label'].map({'01-whole':'whole', '00-damage':'damage'})
test_df['label'] = test_df['label'].map({'01-whole':'whole', '00-damage':'damage'})

train_df

test_df

train_generator = ImageDataGenerator(
    preprocessing_function = preprocess_input,
    rotation_range = 20,
    zoom_range = 0.15,
    horizontal_flip = True,
    height_shift_range = 0.2,
    width_shift_range = 0.2

    )

test_generator = ImageDataGenerator(
    preprocessing_function = preprocess_input,
)

train_data = train_generator.flow_from_dataframe(
    train_df,
    x_col = 'filepath',
    y_col = 'label',
    target_size = (224,224),
    batch_size = 32,
    class_mode = 'binary',
    shuffle=True
)

test_data = test_generator.flow_from_dataframe(
    test_df,
    x_col = 'filepath',
    y_col = 'label',
    target_size = (224,224),
    batch_size = 32,
    class_mode = 'binary',
    shuffle=False
)

from PIL import Image
import os

image_path = "/content/dataset_org/data1a/training/00-damage/0002.JPEG"
img = Image.open(image_path)

print("Width:", img.width)
print("Height:", img.height)
print("Size:", img.size)

from tensorflow.keras.layers import Input,Dense,Dropout,GlobalAveragePooling2D, BatchNormalization,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.utils import plot_model

base_model = EfficientNetV2B3(
    weights = 'imagenet',
    include_top = False,
    input_shape = (224,224,3)
)

base_model.trainable = False

inputs = Input(shape = (224,224,3))
x = base_model(inputs,training = False)
x = GlobalAveragePooling2D()(x)

x = Dense(128,activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

outputs = Dense(1, activation="sigmoid")(x)

# Final model
model = Model(inputs, outputs)

model.summary()

plot_model(
    model,                     # your model
    show_shapes=True,          # display layer output shapes
    show_layer_names=True,     # display layer name
)

model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

history = model.fit(train_data,epochs=10,validation_data=test_data,verbose=1)

model.save('car_damage.keras')

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input

# Path to a single test image
img_path = '/content/2721.jpg'

# Load image, resize to model input
img = image.load_img(img_path, target_size=(224, 224))

# Convert to array and expand dims (batch size = 1)
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# Preprocess for EfficientNetV2
img_array = preprocess_input(img_array)

# Make prediction
pred = model.predict(img_array)

# Interpret output (binary classification)
if pred[0][0] > 0.5:
    print("Predicted class: whole")
else:
    print("Predicted class: damage")

print("Raw prediction:", pred[0][0])