# # -*- coding: utf-8 -*-
# """cat_and-dog.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1nfR-buX0WgLZTEHLADTwlDqbG5IvG4-Q
# """

# from google.colab import files
# files.upload()

# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json

# !kaggle datasets download -d 'anubhab098/cat-vs-dog-dataset'

# import zipfile
# with zipfile.ZipFile('/content/cat-vs-dog-dataset.zip','r') as zip_ref:
#   zip_ref.extractall('/content/dataset')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

EPOCHS = 20
BS = 32

DIRECTORY = '/content/dataset/train'
CATEGORY = ['Cat','Dog']

data = []

for directory in os.listdir(DIRECTORY):
  path = os.path.join(DIRECTORY,directory)
  for img in os.listdir(path):
    data.append([os.path.join(path,img),directory])

df = pd.DataFrame(data,columns=['filepath','animal'])
df['animal'].value_counts()

from PIL import Image

img = Image.open('/content/dataset/train/Cat/cat.10.jpg')
plt.imshow(img)
plt.axis('off')

# X = df['filepath']
# y = df['animal']

from sklearn.model_selection import train_test_split

train_df,test_df = train_test_split(df,test_size=0.2,shuffle = True,stratify=df['animal'],random_state=42)

train_df

from PIL import Image
import os

image_path = "/content/dataset/train/Dog/dog.11495.jpg"
img = Image.open(image_path)

print("Width:", img.width)
print("Height:", img.height)
print("Size:", img.size)  # (

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_data_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range = 20,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    zoom_range = 0.15,
    horizontal_flip = True

)

test_data_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
)

train_generator = train_data_gen.flow_from_dataframe(
    train_df,
    x_col = 'filepath',
    y_col = 'animal',
    target_size = (224,224),
    batch_size = BS,
    class_mode = 'binary'
)

test_generator = test_data_gen.flow_from_dataframe(
    test_df,
    x_col = 'filepath',
    y_col = 'animal',
    target_size = (224,224),
    batch_size = BS,
    class_mode = 'binary'
)

from keras.layers import *
from keras.optimizers import Adam
from keras.models import Model

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Input, Dense, Dropout, GlobalAveragePooling2D, BatchNormalization
from tensorflow.keras.models import Model

# Base model (pretrained MobileNetV2)
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze base model
base_model.trainable = False

# Input layer
inputs = Input(shape=(224, 224, 3))

# Feature extraction
x = base_model(inputs, training=False)   # ✅ use training=False, not trainable=False
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation="relu")(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

# Output layer
outputs = Dense(1, activation="sigmoid")(x)

# Final model
model = Model(inputs, outputs)

model.summary()

model.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics=['accuracy'])

model.fit(train_generator,validation_data=test_generator,epochs=3, verbose=1)

model.save("cnn_mobilenetv2_model.keras")

